CMD: 'python train.py'

HPARAMS: [
  {
    # runx
    logdir: LOGDIR,
    # loss
    loss_type: ['mse'],
    # data
    filename: ['futures_prop.csv'],
    start_date: ['01/01/1990'],
    test_date: ['01/01/2010'],
    end_date: ['01/01/2015'],
    # window
    win_len: [60],
    step: [20],
    # training
    epochs: [50],
    lr: [0.001],
    batch_size: [64],
    dropout: [0.1],
    # --- ---
    # all params above are inherited in the next runs
    # --- ---
    # architecture specific
    RUNX.TAG: 'transformer',
    arch: 'transformer',
    # model hyperparams
    d_model: [60, 240],
    n_head: [6],
    n_layer: [1,2],
    d_hidden_factor: [2, 4], # replace with a factor
  },
  {
    RUNX.TAG: 'conv_transformer',
    arch: 'conv_transformer',
    conv_len: [1, 3, 9]
  },
  {
    RUNX.TAG: 'informer',
    arch: 'informer',
  }
]
