CMD: 'python train.py'

HPARAMS: [
  {
    # runx
    logdir: LOGDIR,
    # main
    loss_type: 'sharpe',
    scaler: 'none',
    # data
    filename: ['futures_prop.csv'],
    start_date: ['01/01/1990'],
    end_date: ['01/01/2020'],
    test_date: ['01/01/2015'],
    # window
    win_len: [60],
    step: [10],
    # training
    epochs: 200,
    patience: 25,
    lr: [0.001],
    max_grad_norm: [0.3],
    dropout: [0, 0.1, 0.3],
    batch_size: [64],
    # --- ---
    # all params above are inherited in the next runs
    # --- ---
    # architecture specific
    arch: 'lstm',
    # model hyperparams
    d_model: [20],
    n_layer: [1]
  }
]
