CMD: 'python train.py'

HPARAMS: [
  {
    # runx
    logdir: LOGDIR,
    # loss
    loss_type: 'sharpe',
    scaler: 'none',
    # data
    filename: ['futures_prop.csv'],
    test_win: 5,
    start_date: ['01/01/1990'],
    test_date: ['01/01/1995'],
    end_date: ['01/01/2020'],
    # window
    win_len: [63],
    step: [63],
    # training
    epochs: [300],
    lr: [0.001],
    batch_size: [64],
    dropout: [0],
    patience: 25,
    max_grad_norm: 0.5,
    # architecture specific
    arch: 'lstm',
    n_layer: 1,
    d_hidden: [40]
  }
]
