CMD: 'python train.py'

HPARAMS: [
  {
    # runx
    logdir: LOGDIR,
    # loss
    loss_type: 'sharpe',
    scaler: 'none',
    # data
    filename: ['futures_prop.csv'],
    test_win: 5,
    start_date: ['01/01/1990'],
    test_date: ['01/01/1995'],
    end_date: ['11/01/2020'],
    # window
    win_len: [63],
    step: [63],
    # training
    epochs: [300],
    lr: [0.01, 0.001, 0.0001],
    batch_size: [64, 128],
    dropout: [0, 0.1, 0.3, 0.5],
    patience: 25,
    max_grad_norm: [1, 0.1],
    # architecture specific
    arch: 'transformer',
    # model hyperparams
    d_hidden: [10, 30, 80],
    d_model: [60, 120],
    n_head: [6, 12],
    n_layer: [1, 2],
    d_hidden_factor: [2, 4], # replace with a factor
  }
]