CMD: 'python train.py'

HPARAMS: [
  {
    # runx
    logdir: LOGDIR,
    # loss
    loss_type: 'sharpe',
    scaler: 'minmax',
    # data
    filename: ['futures_prop.csv'],
    start_date: ['01/01/1990'],
    test_date: ['01/01/2015'],
    end_date: ['17/10/2020'],
    # window
    win_len: [63],
    step: [5],
    # training
    epochs: [100],
    lr: [0.0001],
    batch_size: [128],
    dropout: [0.1],
    patience: 10,
    # --- ---
    # all params above are inherited in the next runs
    # --- ---
    # architecture specific
    RUNX.TAG: 'transformer_2015',
    arch: 'transformer',
    # model hyperparams
    d_model: [60],
    n_head: [12],
    n_layer: [1],
    d_hidden_factor: [2], # replace with a factor
  }, 
  {
    RUNX.TAG: 'transformer_2010',
    test_date: ['01/01/2010'],
  },
  {
    RUNX.TAG: 'transformer_2005',
    test_date: ['01/01/2005'],
  },
  {
    RUNX.TAG: 'transformer_2000',
    test_date: ['01/01/2000'],
  },
  {
    RUNX.TAG: 'transformer_1995',
    test_date: ['01/01/1995'],
  }
]