CMD: 'python train.py'

HPARAMS: [
  {
    # runx
    logdir: LOGDIR,
    # loss
    loss_type: 'sharpe',
    scaler: 'none',
    # data
    filename: ['futures_prop.csv'],
    test_win: 5,
    start_date: ['01/01/1990'],
    test_date: ['01/01/1995'],
    end_date: ['01/01/2020'],
    # window
    win_len: [63],
    step: [63],
    # training
    epochs: [300],
    lr: [0.01],
    batch_size: [128],
    dropout: [0.1],
    patience: 25,
    max_grad_norm: [0.1],
    # architecture specific
    arch: 'transformer',
    # model hyperparams,
    d_hidden: [80]
    d_model: [60],
    n_head: [12],
    n_layer: [1],
    d_hidden_factor: [2], # replace with a factor
  }
]