CMD: 'python train.py'

HPARAMS: [
  {
    # runx
    logdir: LOGDIR,
    # loss
    loss_type: 'sharpe',
    scaler: 'minmax',
    # data
    filename: ['futures_prop.csv'],
    start_date: ['01/01/1990'],
    test_win: 5,
    test_date: ['01/01/1995'],
    end_date: ['17/10/2020'],
    # window
    win_len: [63],
    step: [63],
    # training
    epochs: [100],
    lr: [0.00001, 0.0001, 0.001, 0.01],
    batch_size: [128, 256, 512],
    patience: 25,
    # --- ---
    # all params above are inherited in the next runs
    # --- ---
    # architecture specific
    RUNX.TAG: 'lstm',
    arch: 'lstm',
    # model hyperparams
    n_layer: 1,
    d_model: [20, 40, 80, 160],
    dropout: [0.9, 0.7, 0.5]
  }
]