CMD: 'python train.py'

HPARAMS: [
  {
    # runx
    logdir: LOGDIR,
    # loss
    loss_type: 'sharpe',
    scaler: 'none',
    # data
    filename: ['futures_prop.csv'],
    test_win: 5,
    start_date: ['01/01/1990'],
    test_date: ['01/01/1995'],
    end_date: ['11/01/2020'],
    # window
    win_len: [63],
    step: [63],
    # training
    epochs: [300],
    lr: [0.001],
    batch_size: [128],
    dropout: [0.1, 0.3, 0.5, 0.7],
    patience: 25,
    max_grad_norm: [1, 0.05],
    # architecture specific
    arch: 'transformer',
    # model hyperparams
    d_model: [16, 24, 32, 60],
    n_head: [4, 8],
    n_layer: [1],
    d_hidden_factor: [2, 4], # replace with a factor
  }
]